---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-bot
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord
  namespace: flux-system
spec:
  summary: "Cluster addons impacted in Proxmox Hosted DEV Cluster"
  providerRef:
    name: discord-bot
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
