apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: default
spec:
  targetNamespace: nginx-ingress
  install:
    createNamespace: True
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: default
      interval: 10m
