apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: default
  labels:
    kustomize.toolkit.fluxcd.io/name: podinfo
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: podinfo-lb
spec:
  type: LoadBalancer
  ports:
  - name: port-1
    port: 9898
    protocol: TCP
    targetPort: 9898
  - name: port-2
    port: 9797
    protocol: TCP
    targetPort: 9797
  - name: port-3
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: podinfo
status:
  loadBalancer: {}
