apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  targetNamespace: longhorn-system
  install:
    createNamespace: True
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: '1.7.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 10m
